from backend.config.secrets import ACTIVEMQ_CREDENTIALS

ACTIVEMQ_USER = ACTIVEMQ_CREDENTIALS['user']
ACTIVEMQ_PASSWORD = ACTIVEMQ_CREDENTIALS['password']
ACTIVEMQ_HOST = ACTIVEMQ_CREDENTIALS['host']
ACTIVEMQ_PORT = ACTIVEMQ_CREDENTIALS['port']
ACTIVEMQ_DESTINATION = ACTIVEMQ_CREDENTIALS['destination']