from backend.config.secrets import INFLUXDB_CREDENTIALS

INFLUXDB_TOKEN = INFLUXDB_CREDENTIALS['token']
INFLUXDB_ORG = INFLUXDB_CREDENTIALS['org']
INFLUXDB_BUCKET = INFLUXDB_CREDENTIALS['bucket']
INFLUXDB_URL = INFLUXDB_CREDENTIALS['url']

