from backend.config.secrets import POSTGRES_CREDENTIALS

PG_USER = POSTGRES_CREDENTIALS['user']
PG_DATABASE = POSTGRES_CREDENTIALS['dbname']
PG_PASSWORD = POSTGRES_CREDENTIALS['password']
PG_HOST = POSTGRES_CREDENTIALS['host']
PG_PORT = POSTGRES_CREDENTIALS['port']
