# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stocks_pb2 as stocks__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stocks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegisteringTransactionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFund = channel.unary_unary(
                '/RegisteringTransaction/GetFund',
                request_serializer=stocks__pb2.DbID.SerializeToString,
                response_deserializer=stocks__pb2.FundResponse.FromString,
                _registered_method=True)
        self.GetShareQty = channel.unary_unary(
                '/RegisteringTransaction/GetShareQty',
                request_serializer=stocks__pb2.ShareQuery.SerializeToString,
                response_deserializer=stocks__pb2.ShareQtyResponse.FromString,
                _registered_method=True)
        self.Buy = channel.unary_unary(
                '/RegisteringTransaction/Buy',
                request_serializer=stocks__pb2.NotingTransaction.SerializeToString,
                response_deserializer=stocks__pb2.Message.FromString,
                _registered_method=True)
        self.Sell = channel.unary_unary(
                '/RegisteringTransaction/Sell',
                request_serializer=stocks__pb2.NotingTransaction.SerializeToString,
                response_deserializer=stocks__pb2.Message.FromString,
                _registered_method=True)
        self.GetShareLivePrice = channel.unary_unary(
                '/RegisteringTransaction/GetShareLivePrice',
                request_serializer=stocks__pb2.ShareSymbol.SerializeToString,
                response_deserializer=stocks__pb2.SharePrice.FromString,
                _registered_method=True)


class RegisteringTransactionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareQty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Buy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareLivePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisteringTransactionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFund': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFund,
                    request_deserializer=stocks__pb2.DbID.FromString,
                    response_serializer=stocks__pb2.FundResponse.SerializeToString,
            ),
            'GetShareQty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareQty,
                    request_deserializer=stocks__pb2.ShareQuery.FromString,
                    response_serializer=stocks__pb2.ShareQtyResponse.SerializeToString,
            ),
            'Buy': grpc.unary_unary_rpc_method_handler(
                    servicer.Buy,
                    request_deserializer=stocks__pb2.NotingTransaction.FromString,
                    response_serializer=stocks__pb2.Message.SerializeToString,
            ),
            'Sell': grpc.unary_unary_rpc_method_handler(
                    servicer.Sell,
                    request_deserializer=stocks__pb2.NotingTransaction.FromString,
                    response_serializer=stocks__pb2.Message.SerializeToString,
            ),
            'GetShareLivePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareLivePrice,
                    request_deserializer=stocks__pb2.ShareSymbol.FromString,
                    response_serializer=stocks__pb2.SharePrice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RegisteringTransaction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RegisteringTransaction', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegisteringTransaction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegisteringTransaction/GetFund',
            stocks__pb2.DbID.SerializeToString,
            stocks__pb2.FundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareQty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegisteringTransaction/GetShareQty',
            stocks__pb2.ShareQuery.SerializeToString,
            stocks__pb2.ShareQtyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Buy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegisteringTransaction/Buy',
            stocks__pb2.NotingTransaction.SerializeToString,
            stocks__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegisteringTransaction/Sell',
            stocks__pb2.NotingTransaction.SerializeToString,
            stocks__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareLivePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegisteringTransaction/GetShareLivePrice',
            stocks__pb2.ShareSymbol.SerializeToString,
            stocks__pb2.SharePrice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
