# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stocks.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'stocks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstocks.proto\"\x14\n\x04\x44\x62ID\x12\x0c\n\x04\x64\x62id\x18\x01 \x01(\t\"\x1d\n\x0bShareSymbol\x12\x0e\n\x06symbol\x18\x01 \x01(\t\":\n\nSharePrice\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\x05price\x18\x02 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_price\"\\\n\x11NotingTransaction\x12\x0c\n\x04\x64\x62id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"*\n\nShareQuery\x12\x0c\n\x04\x64\x62id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"\x1f\n\x10ShareQtyResponse\x12\x0b\n\x03qty\x18\x01 \x01(\x05\"\x1c\n\x0c\x46undResponse\x12\x0c\n\x04\x66und\x18\x01 \x01(\x02\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe3\x01\n\x16RegisteringTransaction\x12\x1f\n\x07GetFund\x12\x05.DbID\x1a\r.FundResponse\x12-\n\x0bGetShareQty\x12\x0b.ShareQuery\x1a\x11.ShareQtyResponse\x12#\n\x03\x42uy\x12\x12.NotingTransaction\x1a\x08.Message\x12$\n\x04Sell\x12\x12.NotingTransaction\x1a\x08.Message\x12.\n\x11GetShareLivePrice\x12\x0c.ShareSymbol\x1a\x0b.SharePriceB!Z\x1ftrade-service/goprotos;goprotosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stocks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037trade-service/goprotos;goprotos'
  _globals['_DBID']._serialized_start=16
  _globals['_DBID']._serialized_end=36
  _globals['_SHARESYMBOL']._serialized_start=38
  _globals['_SHARESYMBOL']._serialized_end=67
  _globals['_SHAREPRICE']._serialized_start=69
  _globals['_SHAREPRICE']._serialized_end=127
  _globals['_NOTINGTRANSACTION']._serialized_start=129
  _globals['_NOTINGTRANSACTION']._serialized_end=221
  _globals['_SHAREQUERY']._serialized_start=223
  _globals['_SHAREQUERY']._serialized_end=265
  _globals['_SHAREQTYRESPONSE']._serialized_start=267
  _globals['_SHAREQTYRESPONSE']._serialized_end=298
  _globals['_FUNDRESPONSE']._serialized_start=300
  _globals['_FUNDRESPONSE']._serialized_end=328
  _globals['_MESSAGE']._serialized_start=330
  _globals['_MESSAGE']._serialized_end=356
  _globals['_REGISTERINGTRANSACTION']._serialized_start=359
  _globals['_REGISTERINGTRANSACTION']._serialized_end=586
# @@protoc_insertion_point(module_scope)
